// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQ8oaUmZ_OaUchKu6GI94dTLpW3LH9EI',
    appId: '1:979011566073:web:3718807bcf41f8dce12528',
    messagingSenderId: '979011566073',
    projectId: 'fir-notes-c86b7',
    authDomain: 'fir-notes-c86b7.firebaseapp.com',
    storageBucket: 'fir-notes-c86b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_z7sqJkRrN_IE5uMc9QBv2GMJCr1f7e4',
    appId: '1:979011566073:android:4866a6f421ec65e2e12528',
    messagingSenderId: '979011566073',
    projectId: 'fir-notes-c86b7',
    storageBucket: 'fir-notes-c86b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp-tBIRX1DSGueKbc1Y0CqHjKdRATDvAg',
    appId: '1:979011566073:ios:625bf4aef78b668ee12528',
    messagingSenderId: '979011566073',
    projectId: 'fir-notes-c86b7',
    storageBucket: 'fir-notes-c86b7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesAppTokareva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp-tBIRX1DSGueKbc1Y0CqHjKdRATDvAg',
    appId: '1:979011566073:ios:625bf4aef78b668ee12528',
    messagingSenderId: '979011566073',
    projectId: 'fir-notes-c86b7',
    storageBucket: 'fir-notes-c86b7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesAppTokareva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJQ8oaUmZ_OaUchKu6GI94dTLpW3LH9EI',
    appId: '1:979011566073:web:68dc74e7a75f31c4e12528',
    messagingSenderId: '979011566073',
    projectId: 'fir-notes-c86b7',
    authDomain: 'fir-notes-c86b7.firebaseapp.com',
    storageBucket: 'fir-notes-c86b7.firebasestorage.app',
  );
}
